### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [huku29/film_connect_back#33]
※ 確認後closeしてください

## サービスレビュー
* デザインなどから映画の雰囲気が出ていてよかったかなと思います。
* ただ映画レターという概念自体が難しすぎる（分かりづらい）為、とっつきづらいと思ったのでみんなのオススメ映画を受け取るという形でレターを無理に入れないで考えたほうがいいかなと思いました。
* UIが分かりづらかったので、第三者に初見で使ってもらいながらインタビューをしたほうがいいかなと思います。個人的にはトップページにボタンが何もなかったり、マイページに行かないと何も出来なかったり、ランダムのところでも何をすればいいか迷うなど、初見で使うにはつらかったなと思いました。

## コードレビュー

* すいません、フロント苦手なのでバックエンドだけ

https://github.com/huku29/film_connect_back/blob/f3a9be82c17e917577da10d4538b038f4b4d326d/app/controllers/api/v1/not_watch_film_letters_controller.rb#L11

```
not_watch_films  = current_user.not_watch_film_letters
```
で取れますよね？リレーションでうまく取得しましょう。

https://github.com/huku29/film_connect_back/blob/f3a9be82c17e917577da10d4538b038f4b4d326d/app/controllers/api/v1/not_watch_film_letters_controller.rb#L26-L27

```
letters = Letter.joins(:not_watch_film_letter_movies).merge(NotWatchFilmLetter.all)
```
みたいな形で取得できそうだなと思いました。pluckを使うとSQL上はinになり、中身が増えると実行コストが高くなるので、うまくjoinを使いましょう（上記動くかわかりませんが、JOINされて取得できればOKです）

https://github.com/huku29/film_connect_back/blob/f3a9be82c17e917577da10d4538b038f4b4d326d/app/controllers/api/v1/not_watch_film_letters_controller.rb#L39

これ、findにすればallいらないですよね？単体のインスタンスを取得するのかActiveRecord::Relationを取得するのかなど戻り値が何かを意識されるとよいかと思います。

* その他上記と同様のコードも多いと思うので、1つ1つ理解してリファクタしてみてください。

**Comment by huku29** [comment]
ひさじゅさんレビューありがとうございます🙇🏻‍♂️
上記指摘された点を自分なりに落とし込んでいき、改善に努めていきたいと思います！
